Repository pylejeune/norug-fun, pull requests merged in 2025-05, with the labels that each got.

#98 72 feature creation reclaim support pour les proposals rejected
  programs/programs/programs/src/error.rs
  programs/programs/programs/src/instructions/mod.rs
  programs/programs/programs/src/instructions/reclaim_support.rs
  programs/programs/programs/src/lib.rs
  programs/tests/reclaim.test.ts
Labels: backend, PRIORITY 0

#105 feat(front): apply military theme styling to WalletMultiButton
  front/app/[locale]/layout.tsx
  front/app/globals.css
  front/components/layout/Header.tsx
Labels: frontend

#103 feat(front): display proposals as list and add typewriter slogan
  front/app/[locale]/page.tsx
  front/app/globals.css
  front/components/home/ActiveProposalsView.tsx
  front/components/home/ProposalCard.tsx
  front/components/home/ViewModeToggle.tsx
  front/components/ui/typewriter-effect.tsx
  front/lib/utils.ts
  front/package-lock.json
  front/package.json
Labels: frontend

#108 feat(legal-pages): complete first version of legal pages
  front/app/[locale]/(legal-pages)/privacy/page.tsx
  front/app/[locale]/(legal-pages)/terms/page.tsx
  front/messages/en.json
  front/messages/fr.json
Labels: frontend

#110 109 feature ajouter lupload dimage ipfs dans le formulaire de création de token proposal
  front/app/[locale]/mypage/page.tsx
  front/app/[locale]/proposal/[id]/page.tsx
  front/components/ProposalForm.tsx
  front/components/home/ProposalCard.tsx
  front/context/ProgramContext.tsx
  front/messages/en.json
  front/messages/fr.json
  front/next.config.mjs
  front/package-lock.json
  front/package.json
  front/utils/ImageStorage.ts
Labels: frontend, feature

#120 119 feature consultation des tokens créés et soutenus par dautres utilisateurs via adresse solana
  front/app/[locale]/mypage/page.tsx
  front/app/[locale]/profile/[id]/page.tsx
  front/components/home/ProposalCard.tsx
  front/components/layout/AltSidebar.tsx
  front/components/profile/ProfileImage.tsx
  front/messages/en.json
  front/messages/fr.json
  front/public/images/default-profile.png
Labels: frontend, feature

#118 44 feature afficher les proposal support dun proposal token
  front/app/[locale]/proposal/[id]/page.tsx
  front/components/proposal/ProposalSupportList.tsx
  front/context/ProgramContext.tsx
  front/messages/en.json
  front/messages/fr.json
Labels: frontend, feature

#129 feat: add wallet links and fix multiple proposal support
  front/app/[locale]/proposal/[id]/page.tsx
  front/components/proposal/ProposalSupportList.tsx
  front/context/ProgramContext.tsx
Labels: frontend, feature

#126 121 feature treasury and roles
  programs/programs/programs/src/constants.rs
  programs/programs/programs/src/error.rs
  programs/programs/programs/src/instructions/create_token_proposal.rs
  programs/programs/programs/src/instructions/initialize_treasury.rs
  programs/programs/programs/src/instructions/manage_treasury_role.rs
  programs/programs/programs/src/instructions/mod.rs
  programs/programs/programs/src/instructions/support_proposal.rs
  programs/programs/programs/src/lib.rs
  programs/programs/programs/src/state/mod.rs
  programs/programs/programs/src/utils/fee_distribution.rs
  programs/programs/programs/src/utils/mod.rs
  programs/tests/crank_simulation.test.ts
  programs/tests/proposal.test.ts
  programs/tests/reclaim.test.ts
  programs/tests/treasury_roles.test.ts
Labels: backend

#131 130 chore add timestamp to create proposal
  programs/programs/programs/src/instructions/create_token_proposal.rs
  programs/programs/programs/src/state/mod.rs
  programs/tests/proposal.test.ts
Labels: backend

#136 feat(claim): add claim button to profile and proposal pages
  front/app/[locale]/profile/[id]/page.tsx
  front/app/[locale]/proposal/[id]/page.tsx
  front/context/ProgramContext.tsx
  front/messages/en.json
  front/messages/fr.json
Labels: frontend, feature

#159 146 chore aide decision total supply
  front/components/ProposalForm.tsx
  front/components/TotalSupplyInfoDialog.tsx
  front/components/ui/dialog.tsx
  front/components/ui/label.tsx
  front/components/ui/radio-group.tsx
  front/components/ui/table.tsx
  front/messages/en.json
  front/messages/fr.json
  front/package-lock.json
  front/package.json
Labels: frontend

#170 [Feature] Tri par timestamp des proposals + Ajout d'un .env pour le front
  front/.env.example
  front/.gitignore
  front/app/[locale]/profile/[id]/page.tsx
  front/app/[locale]/proposal/[id]/page.tsx
  front/components/home/ActiveProposalsView.tsx
  front/components/home/ProposalCard.tsx
  front/context/ProgramContext.tsx
  front/context/idl/programs.json
  front/context/types/programs.ts
  front/messages/en.json
  front/messages/fr.json
Labels: frontend, feature

#191 chore: add logger to catch logs to a file
  front/.env.example
  front/app/[locale]/layout.tsx
  front/utils/logger.ts
Labels: feature

#186 chore: refactor idl files and utils
  front/app/api/cron/crank/route.ts
  front/app/api/cron/crank/service.ts
  front/app/api/cron/epoch-scheduler/route.ts
  front/app/api/cron/epoch-scheduler/service.ts
  front/app/api/cron/shared/programs.json
  front/app/api/cron/shared/utils.ts
  front/app/api/proposal/create/route.ts
  front/app/api/proposal/create/service.ts
  front/app/api/proposal/list/route.ts
  front/app/api/shared/programs.json
  front/app/api/shared/utils.ts
  front/app/api/treasury/balance/route.ts
  front/app/api/treasury/initialize/route.ts
  front/app/api/treasury/initialize/service.ts
  front/app/idl/programs.json
  front/context/ProgramContext.tsx
  front/context/program.ts
  front/idl/programs.json
  front/idl/programs.ts
  front/lib/utils.ts
  programs/scripts/copy-idl.js
  programs/scripts/copy-types.js
Labels: frontend

#212 [Chore] Application des règles de linting & formatting sur le code existant
  front/app/[locale]/archive/page.tsx
  front/app/[locale]/epoch/page.tsx
  front/app/[locale]/howitworks/loading.tsx
  front/app/[locale]/howitworks/page.tsx
  front/app/[locale]/page.tsx
  front/app/[locale]/profile/[id]/page.tsx
  front/app/[locale]/proposal/[id]/page.tsx
  front/app/[locale]/treasury/page.tsx
  front/app/api/cron/crank/service.ts
  front/app/api/cron/epoch-scheduler/route.ts
  front/app/api/cron/epoch-scheduler/service.ts
  front/app/api/epoch/close-all/route.ts
  front/app/api/epoch/close-all/service.ts
  front/app/api/epoch/create/route.ts
  front/app/api/epoch/create2min/route.ts
  front/app/api/epoch/create48h/route.ts
  front/app/api/epoch/service.ts
  front/app/api/hello/route.js
  front/app/api/programconfig/info/route.ts
  front/app/api/programconfig/info/service.ts
  front/app/api/programconfig/initialize/route.ts
  front/app/api/programconfig/initialize/service.ts
  front/app/api/programconfig/keyinfo/route.ts
  front/app/api/proposal/create/image-service.ts
  front/app/api/proposal/create/route.ts
  front/app/api/proposal/create/service.ts
  front/app/api/proposal/list/route.ts
  front/app/api/treasury/balance/route.ts
  front/app/api/treasury/balance/service.ts
  front/app/api/treasury/initialize/route.ts
  front/components/EpochForm.tsx
  front/components/ProposalForm.tsx
  front/components/TotalSupplyInfoDialog.tsx
  front/components/epoch/EpochList.tsx
  front/components/layout/AltSidebar.tsx
  front/components/layout/Header.tsx
  front/components/profile/ProfileImage.tsx
  front/context/ProgramContext.tsx
  front/lib/utils.ts
  front/messages/en.json
  front/messages/fr.json
  front/package-lock.json
  front/package.json
Labels: frontend

#201 chore: Configuration ESLint, Prettier & règles VSCode
  front/.eslintrc.json
  front/.prettierignore
  front/.prettierrc
  front/.vscode/extensions.json
  front/.vscode/settings.json
  front/app/api/shared/programs.json
  front/app/api/shared/utils.ts
  front/context/idl/programs.json
  front/package-lock.json
  front/package.json
Labels: documentation

#221 205 chore tests sub 4 refactoriser les tests du module treasury setup and roles
  package.json
  programs/Anchor.toml
  programs/package.json
  programs/programs/programs/src/error.rs
  programs/programs/programs/src/instructions/manage_treasury_role.rs
  programs/tests/archives/epoch.test.ts
  programs/tests/archives/epoch_scheduler.test.ts
  programs/tests/archives/programconfig.test.ts
  programs/tests/archives/treasury_roles.test.ts
  programs/tests/crank_simulation.test.ts
  programs/tests/integration/00_program_configuration/initializeProgramConfig.test.ts
  programs/tests/integration/00_program_configuration/programConfig.test.ts
  programs/tests/integration/01_epoch_lifecycle/endEpoch.test.ts
  programs/tests/integration/01_epoch_lifecycle/markEpochProcessed.test.ts
  programs/tests/integration/01_epoch_lifecycle/startEpoch.test.ts
  programs/tests/integration/02_treasury_and_roles/initializeTreasury.test.ts
  programs/tests/integration/02_treasury_and_roles/initializeTreasuryRoles.test.ts
  programs/tests/integration/02_treasury_and_roles/roles_management/addAdmin.test.ts
  programs/tests/integration/02_treasury_and_roles/roles_management/addTreasuryRole.test.ts
  programs/tests/integration/02_treasury_and_roles/roles_management/removeAdmin.test.ts
  programs/tests/integration/02_treasury_and_roles/roles_management/removeTreasuryRole.test.ts
  programs/tests/integration/02_treasury_and_roles/roles_management/updateTreasuryRole.test.ts
  programs/tests/main.test.ts
  programs/tests/reclaim.test.ts
  programs/tests/setup/epochSetup.ts
  programs/tests/setup/index.ts
  programs/tests/setup/programConfigSetup.ts
  programs/tests/setup/proposalSetup.ts
  programs/tests/setup/treasurySetup.ts
  programs/tests/utils_for_tests/constants.ts
  programs/tests/utils_for_tests/helpers.ts
Labels: backend
