Repository pylejeune/norug-fun, pull requests merged in 2025-04, with the labels that each got.

#31 feat: create epoch and token proposal
  programs/Anchor.toml
  programs/package-lock.json
  programs/package.json
  programs/programs/programs/src/error.rs
  programs/programs/programs/src/instructions/initialize.rs
  programs/programs/programs/src/lib.rs
  programs/tests/programs.ts
  programs/tsconfig.json
  programs/yarn.lock
Labels: rust, backend, feature

#33 feat(front): add initial pages structure
  front/app/[locale]/(legal-pages)/privacy/page.tsx
  front/app/[locale]/(legal-pages)/terms/page.tsx
  front/app/[locale]/archive/page.tsx
  front/app/[locale]/create/page.tsx
  front/app/[locale]/epoch/page.tsx
  front/app/[locale]/layout.tsx
  front/app/[locale]/loading.tsx
  front/app/[locale]/page.tsx
  front/app/[locale]/proposal/[id]/page.tsx
  front/app/[locale]/treasury/page.tsx
  front/app/globals.css
  front/components/ProposalForm.tsx
  front/components/layout/AltSidebar.tsx
  front/components/layout/Footer.tsx
  front/components/layout/Header.tsx
  front/components/ui/button.tsx
  front/components/ui/header.tsx
  front/components/ui/input.tsx
  front/components/ui/separator.tsx
  front/components/ui/sheet.tsx
  front/components/ui/sidebar.tsx
  front/components/ui/skeleton.tsx
  front/components/ui/slider.tsx
  front/components/ui/textarea.tsx
  front/components/ui/tooltip.tsx
  front/components/wallet/AppWalletProvider.tsx
  front/components/wallet/ClientWalletMultiButton.tsx
  front/hooks/use-mobile.ts
  front/messages/en.json
  front/messages/fr.json
  front/package-lock.json
  front/package.json
  front/public/tokenDemo/alpha.png
  front/public/tokenDemo/beta.png
Labels: nextjs, frontend, feature

#35 16 feature creation get epoch state pour epochmanagement
  .cursor/rules/pull-request-template.mdc
  programs/Anchor.toml
  programs/programs/programs/src/error.rs
  programs/programs/programs/src/instructions/create_token_proposal.rs
  programs/programs/programs/src/instructions/get_epoch_state.rs
  programs/programs/programs/src/instructions/mod.rs
  programs/programs/programs/src/instructions/start_epoch.rs
  programs/programs/programs/src/lib.rs
  programs/tests/epoch.test.ts
  programs/tests/proposal.test.ts
  programs/tests/utils.test.ts
  programs/yarn.lock
Labels: rust, backend, feature

#65 65 - Refactorisation du workflow Anchor Tests et résolution du problème avec `proc_macro2`
  .github/workflows/anchor-tests.yml
  .vscode/settings.json
  programs/programs/programs/src/lib.rs
Labels: bug, backend

#64 feat(epoch): connect end epoch and list epoch
  .gitignore
  front/app/[locale]/epoch/page.tsx
  front/components/epoch/EpochList.tsx
  front/context/ProgramContext.tsx
  front/context/idl/programs.json
  front/context/types/programs.ts
  front/messages/en.json
  front/messages/fr.json
  programs/package.json
  programs/scripts/copy-types.js
Labels: frontend, feature

#77 51 feature bouton formulaire creation proposaltoken
  front/app/[locale]/archive/page.tsx
  front/app/[locale]/create/page.tsx
  front/app/[locale]/layout.tsx
  front/app/[locale]/mypage/page.tsx
  front/app/[locale]/page.tsx
  front/app/[locale]/proposal/[id]/page.tsx
  front/app/[locale]/proposal/create/page.tsx
  front/components/ProposalForm.tsx
  front/components/epoch/EpochSelector.tsx
  front/components/home/ActiveProposalsView.tsx
  front/components/home/PreviousEpochsView.tsx
  front/components/home/ProposalCard.tsx
  front/components/home/ViewModeToggle.tsx
  front/components/layout/AltSidebar.tsx
  front/components/layout/Header.tsx
  front/context/ProgramContext.tsx
  front/context/idl/programs.json
  front/context/program.ts
  front/context/types/programs.ts
  front/messages/en.json
  front/messages/fr.json
  front/public/favicon.ico
  front/public/images/logo.svg
  front/public/tokenDemo/alpha.png
  front/public/tokenDemo/beta.png
Labels: bug, nextjs, frontend, feature, PRIORITY 2

#84 82 chore ajouter les champs description et imageurl dans tokenproposal
  programs/programs/programs/src/instructions/create_token_proposal.rs
  programs/programs/programs/src/instructions/get_proposal_details.rs
  programs/programs/programs/src/lib.rs
  programs/programs/programs/src/state/mod.rs
  programs/tests/crank_simulation.test.ts
  programs/tests/proposal.test.ts
  programs/tests/updateproposal.test.ts
Labels: backend

#88 feat(proposal): integration front of description proposal
  front/app/[locale]/mypage/page.tsx
  front/app/[locale]/proposal/[id]/page.tsx
  front/components/ProposalForm.tsx
  front/context/ProgramContext.tsx
  front/context/idl/programs.json
  front/context/types/programs.ts
Labels: frontend, feature

#89 feat(cluster): add option to choose localhost or devnet
  front/components/wallet/AppWalletProvider.tsx
Labels: frontend, feature
